version: '2'

services:
  drone-server:
    image: drone/drone:0.8

    ports:
      - 80:8000
      - 9000
    volumes:
      - /var/lib/drone:/var/lib/drone/
    restart: always
    environment:
      - DRONE_OPEN=true
      - DRONE_HOST=127.0.0.1
      - DRONE_GOGS=true
      - DRONE_GOGS_URL=http://gogs.xxx.com
      - DRONE_GOGS_PRIVATE_MODE=true
      - DRONE_SECRET=f5b8122b5e1cf51da10d3be6e25bf6ec
      - DRONE_DATABASE_DRIVER=mysql
      - DRONE_DATABASE_DATASOURCE=root:123456@tcp(10.xx.xx.126:3306)/drone?parseTime=true

  drone-agent:
    image: drone/agent:0.8

    restart: always
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_SERVER=drone-server:9000
      - DRONE_SECRET=f5b8122b5e1cf51da10d3be6e25bf6ec
      - DOCKER_API_VERSION=1.24